import fs from "fs/promises";
import esbuild from "esbuild";

const srcDir = "src/styles";
const outFile = "src/core/base-css.js";
const files = [
    "tokens.css",
    "base.css",
    "tooltips.css",
    "hud.css",
    "overlays.css",
    "panel.css",
];

try {
    const contents = await Promise.all(
        files.map(async (file) => {
            const css = await fs.readFile(`${srcDir}/${file}`, "utf8");
            const { code } = await esbuild.transform(css, {
                loader: "css",
                minify: true,
            });
            return code;
        })
    );
    const minified = contents.join("");
    const escaped = minified.replace(/`/g, "\\`");
    const output = `// Generated by tools/minify-css.js\nexport const BASE_CSS = \`${escaped}\`;\n`;
    await fs.writeFile(outFile, output);
    console.log(`Wrote ${outFile}.`);
} catch (err) {
    console.error(err);
    process.exit(1);
}
